# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/direct_client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/direct_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/direct_client.proto\x12\x06\x64irect\"o\n\x11SendDirectRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\x0f\n\x07to_user\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x15\n\rclient_msg_id\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\"9\n\x12SendDirectResponse\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x16\n\x0eserver_time_ms\x18\x02 \x01(\x03\"Q\n\x1cSubscribeConversationRequest\x12\x0e\n\x06user_a\x18\x01 \x01(\t\x12\x0e\n\x06user_b\x18\x02 \x01(\t\x12\x11\n\tafter_seq\x18\x03 \x01(\x04\"\x9d\x01\n\x0b\x44irectEvent\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x16\n\x0eserver_time_ms\x18\x02 \x01(\x03\x12\x0e\n\x06user_a\x18\x03 \x01(\t\x12\x0e\n\x06user_b\x18\x04 \x01(\t\x12\x11\n\tfrom_user\x18\x05 \x01(\t\x12\x11\n\tclient_id\x18\x06 \x01(\t\x12\x15\n\rclient_msg_id\x18\x07 \x01(\t\x12\x0c\n\x04text\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.direct_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDDIRECTREQUEST']._serialized_start=38
  _globals['_SENDDIRECTREQUEST']._serialized_end=149
  _globals['_SENDDIRECTRESPONSE']._serialized_start=151
  _globals['_SENDDIRECTRESPONSE']._serialized_end=208
  _globals['_SUBSCRIBECONVERSATIONREQUEST']._serialized_start=210
  _globals['_SUBSCRIBECONVERSATIONREQUEST']._serialized_end=291
  _globals['_DIRECTEVENT']._serialized_start=294
  _globals['_DIRECTEVENT']._serialized_end=451
# @@protoc_insertion_point(module_scope)
