# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import direct_client_pb2 as direct__client__pb2
import direct_gateway_pb2 as direct__gateway__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in direct_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DirectGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDirect = channel.unary_unary(
                '/direct.DirectGateway/SendDirect',
                request_serializer=direct__client__pb2.SendDirectRequest.SerializeToString,
                response_deserializer=direct__client__pb2.SendDirectResponse.FromString,
                _registered_method=True)
        self.SubscribeConversation = channel.unary_stream(
                '/direct.DirectGateway/SubscribeConversation',
                request_serializer=direct__client__pb2.SubscribeConversationRequest.SerializeToString,
                response_deserializer=direct__client__pb2.DirectEvent.FromString,
                _registered_method=True)
        self.GetConversationHistory = channel.unary_unary(
                '/direct.DirectGateway/GetConversationHistory',
                request_serializer=direct__gateway__pb2.GetConversationHistoryRequest.SerializeToString,
                response_deserializer=direct__gateway__pb2.GetConversationHistoryResponse.FromString,
                _registered_method=True)


class DirectGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDirect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDirect': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDirect,
                    request_deserializer=direct__client__pb2.SendDirectRequest.FromString,
                    response_serializer=direct__client__pb2.SendDirectResponse.SerializeToString,
            ),
            'SubscribeConversation': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeConversation,
                    request_deserializer=direct__client__pb2.SubscribeConversationRequest.FromString,
                    response_serializer=direct__client__pb2.DirectEvent.SerializeToString,
            ),
            'GetConversationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationHistory,
                    request_deserializer=direct__gateway__pb2.GetConversationHistoryRequest.FromString,
                    response_serializer=direct__gateway__pb2.GetConversationHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'direct.DirectGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('direct.DirectGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DirectGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDirect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/direct.DirectGateway/SendDirect',
            direct__client__pb2.SendDirectRequest.SerializeToString,
            direct__client__pb2.SendDirectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/direct.DirectGateway/SubscribeConversation',
            direct__client__pb2.SubscribeConversationRequest.SerializeToString,
            direct__client__pb2.DirectEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/direct.DirectGateway/GetConversationHistory',
            direct__gateway__pb2.GetConversationHistoryRequest.SerializeToString,
            direct__gateway__pb2.GetConversationHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
