
FROM ghcr.io/void-linux/void-glibc-busybox

LABEL version="MDC-W2"
LABEL description="Python3; \
          void-glibc-busybox"

RUN xbps-install -Su -y

RUN xbps-install -y python3
RUN xbps-install -y python3-devel
RUN xbps-install -y python3-pip
RUN xbps-install -y python3-virtualenv

ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_BREAK_SYSTEM_PACKAGES=1

ENV DISPLAY=${DISPLAY}
ENV LANG=en_US.UTF-8

EXPOSE 8080
# ENTRYPOINT ["/bin/sh"]